version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    groups:
      types:
        patterns:
          - "@tsconfig/*"
          - "@types/node"
    schedule:
      interval: "weekly"
      time: "21:00"
      timezone: "America/New_York"
    reviewers:
      - "exilesprx"

  - package-ecosystem: "docker"
    directory: ".docker/"
    schedule:
      interval: "weekly"
      time: "21:00"
      timezone: "America/New_York"
    reviewers:
      - "exilesprx"
