version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: ".docker/app"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: ".docker/tests"
    schedule:
      interval: "weekly"