services:

  version:
    image: exilesprx/blockchain:${VERSION}
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: version
      cache_from: 
        - exilesprx/blockchain:source