services:
  bank:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: dev
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules
    entrypoint: pnpm run serve:bank

  miner:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: dev
    volumes:
      - .:/usr/app
      - node_modules:/usr/app/node_modules
    entrypoint: pnpm run serve:miner

volumes:
  node_modules:
