services:
  broker:
    image: apache/kafka:latest
    ports:
      - 9092:9092
    volumes:
      - kafka:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://127.0.0.1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

  bank:
    image: exilesprx/blockchain:bank-${APP_VERSION:-latest}
    container_name: bank
    ports:
      - '3000:3000'
      - '9229:9229'
    depends_on:
      - kurrentdb.db
      - broker
    environment:
      APP_PORT: ${APP_PORT:?}
      APP_NAME: ${APP_NAME:-blockchain}
      APP_ENV: ${APP_ENV:-dev}
      DB_HOST: kurrentdb.db
      DB_PORT: 2113
      DB_INSECURE: true
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID:?}
      KAFKA_CLIENT_ID: ${KAFKA_CLIENT_ID:?}
      KAFKA_HOST: broker
      KAFKA_PORT: 29092
      # GRAYLOG_HOST: graylog
      # GRAYLOG_PORT: 12201

  miner:
    image: exilesprx/blockchain:miner-${APP_VERSION:-latest}
    container_name: miner
    ports:
      - '9230:9229'
    depends_on:
      - broker
    environment:
      APP_PORT: ${APP_PORT:?}
      APP_NAME: ${APP_NAME:-blockchain}
      APP_ENV: ${APP_ENV:-dev}
      DB_HOST: kurrentdb.db
      DB_PORT: 2113
      DB_INSECURE: true
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID:?}
      KAFKA_CLIENT_ID: ${KAFKA_CLIENT_ID:?}
      KAFKA_HOST: broker
      KAFKA_PORT: 29092
      # GRAYLOG_HOST: graylog
      # GRAYLOG_PORT: 12201

  kurrentdb.db:
    image: docker.kurrent.io/kurrent-latest/kurrentdb:latest
    environment:
      - KURRENTDB_CLUSTER_SIZE=1
      - KURRENTDB_RUN_PROJECTIONS=All
      - KURRENTDB_START_STANDARD_PROJECTIONS=true
      - KURRENTDB_NODE_PORT=2113
      - KURRENTDB_INSECURE=true
      - KURRENTDB_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - '2113:2113'
    volumes:
      - type: volume
        source: kurrentdb-volume-data
        target: /var/lib/kurrentdb
      - type: volume
        source: kurrentdb-volume-logs
        target: /var/log/kurrentdb

volumes:
  kafka:
  kurrentdb-volume-data:
  kurrentdb-volume-logs:
