services:
  bank:
    image: exilesprx/blockchain:bank-${VERSION}
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: bank
      cache_from:
        - exilesprx/blockchain:source
  miner:
    image: exilesprx/blockchain:miner-${VERSION}
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: miner
      cache_from:
        - exilesprx/blockchain:source
