services:
  base:
    image: exilesprx/blockchain:base
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: base

  prerelease:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: prerelease

  main:
    image: exilesprx/blockchain:main
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: main
      cache_from:
        - exilesprx/blockchain:base
