services:
  base:
    image: exilesprx/blockchain:base
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: base

  dev:
    build:
      context: .
      dockerfile: .docker/Dockerfile
      target: dev
