# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@5.0

jobs:
  build-app:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - node/install-packages
      - run: npm run build:app

  lint:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint

  test:
    docker:
      - image: cimg/node:16.14.2
    steps:
      - checkout
      - node/install-packages
      - run: npm run test

workflows:
  build-lint-and-test:
    jobs:
      - build-app
      - lint:
          requires:
            - build-app
      - test:
          requires:
            - lint