# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  lint:
    docker:
      - image: cimg/node:16-alpine
    steps:
      - checkout
      - run: npm run lint
      
  build:
    docker:
      - image: cimg/node:16-alpine
    steps:
      - checkout
      - run: npm install

  test:
    docker:
      - image: cimg/node:16-alpine
    steps:
      - node/test

workflows:
  build_lint_and_test:
    jobs:
      - lint
      - build:
        requires:
          - lint
      -test:
        requires:
          - build

