version: '3'
services:
  base:
    image: node:latest
    volumes:
      - ../:/usr/app
    working_dir: /usr/app
  install:
    extends:
      service: base
    stdin_open: true
    tty: true