name: Audit

on:
  push
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  audit:
    runs_on: exilesprx\blockchain:develop
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: pnpm i

      - name: Audit packages
        run: pnpm audit