name: Build actions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          docker compose -f docker-compose.build.yml build prerelease
          docker compose -f docker-compose.build.yml run -v "$PWD/coverage:/usr/app/coverage" prerelease
      - name: Install deps for codecov
        run: |
          sudo apt-get -y update
          sudo apt-get -y install --no-install-recommends gpg
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          directory: ./coverage
          token: ${{ secrets.CODECOV_ORG_TOKEN }}

  typescript-build-bank:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          docker compose -f docker-compose.build.yml build main
          docker compose -f docker-compose.build.yml run main sh -c "pnpm run build:bank"

  typescript-build-miner:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          docker compose -f docker-compose.build.yml build main
          docker compose -f docker-compose.build.yml run main sh -c "pnpm run build:miner"

  docker-build-main:
    runs-on: ubuntu-latest
    needs:
      - typescript-build-bank
      - typescript-build-miner
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: |
          docker compose -f docker-compose.build.yml build main
          docker compose -f docker-compose.build.yml push main
