name: Build actions

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    container: exilesprx/blockchain:source
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules

      - name: Install packages
        run: pnpm i

      - name: Test code
        run: pnpm run test

      - name: Install deps for codecov
        run: |
          apt-get -y update
          apt-get -y install --no-install-recommends curl ca-certificates sudo gpg

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_ORG_TOKEN }}

  build-source:
    runs-on: ubuntu-latest
    needs: test
    container: exilesprx/blockchain:source
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules

      - name: Build bank
        run: pnpm run build:bank

      - name: Build miner
        run: pnpm run build:miner

  build-docker-source:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build source
        run: |
          docker compose -f docker-compose.build.yml build --pull source
          docker compose -f docker-compose.build.yml push source

      - name: Build main
        run: |
          docker compose -f docker-compose.build.yml build --pull main
          docker compose -f docker-compose.build.yml push main