name: Build actions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"

jobs:
  docker-build-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: |
          docker compose -f docker-compose.build.yml build --pull source
          docker compose -f docker-compose.build.yml push source

  install-packages:
    runs-on: ubuntu-latest
    needs: docker-build-source
    container:
      image: exilesprx/blockchain:source
    steps:
      - uses: actions/checkout@v4
      - name: Corepack
        run: corepack install
      - name: Install
        run: pnpm i
      - name: Compress files
        run: tar -czf pnpm-packages.tar.gz node_modules
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pnpm-packages
          path: pnpm-packages.tar.gz

  test:
    runs-on: ubuntu-latest
    needs: install-packages
    container: exilesprx/blockchain:source
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: pnpm-packages
      - name: Extract artifacts
        run: tar -xvf pnpm-packages.tar.gz
      - name: Test code
        run: pnpm run test
      - name: Install deps for codecov
        run: |
          apt-get -y update
          apt-get -y install --no-install-recommends curl ca-certificates sudo gpg git
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_ORG_TOKEN }}

  typescript-build-bank:
    runs-on: ubuntu-latest
    needs: test
    container: exilesprx/blockchain:source
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: pnpm-packages
      - name: Extract artifacts
        run: tar -xvf pnpm-packages.tar.gz
      - name: Build
        run: pnpm run build:bank

  typescript-build-miner:
    runs-on: ubuntu-latest
    needs: test
    container: exilesprx/blockchain:source
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: pnpm-packages
      - name: Extract artifacts
        run: tar -xvf pnpm-packages.tar.gz
      - name: Build
        run: pnpm run build:miner

  docker-build-main:
    runs-on: ubuntu-latest
    needs:
      - typescript-build-bank
      - typescript-build-miner
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: pnpm-packages
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract artifacts
        run: tar -xvf pnpm-packages.tar.gz
      - name: Build
        run: |
          docker compose -f docker-compose.build.yml build --pull main
          docker compose -f docker-compose.build.yml push main

