name: Feature actions

on:
  push:
    branches_ignore:
      - 'main'

jobs:
  lint-typescript:
    runs-on: ubuntu-latest
    container: exilesprx/blockchain:source
    steps:
      - uses: actions/checkout@v3

      - name: Install packges
        run: pnpm i

      - name: Lint code
        run: pnpm run lint

      - name: Upload node modules
        uses: actions/upload-artifact@v3
        with:
          name: node-modules
          path: node_modules

  lint-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint dockerfile
        run: docker run --rm -i -v "$PWD"/hadolint.yml:/.config/hadolint.yaml hadolint/hadolint < .docker/Dockerfile

  audit:
    runs-on: ubuntu-latest
    needs:
      - lint-typescript
      - lint-docker
    container: exilesprx/blockchain:source
    steps:
      - uses: actions/checkout@v3

      - name: Download node modules
        uses: actions/download-artifact@v3
        with: node-modules

      - name: Audit packages
        run: pnpm audit

  test:
    runs-on: ubuntu-latest
    needs: audit
    container: exilesprx/blockchain:source
    steps:
      - uses: actions/checkout@v3

      - name: Download node modules
        uses: actions/download-artifact@v3
        with: node-modules

      - name: Test code
        run: pnpm run test