name: Feature actions

on:
  push:
    branches-ignore:
      - 'main'

#I'm not a fan of redundant builds since it increases build times, but artifacts are also costly
jobs:
  lint-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint dockerfile
        run: docker run --rm -i -v "$PWD"/hadolint.yml:/.config/hadolint.yaml hadolint/hadolint < .docker/Dockerfile

  lint-typescript:
    runs-on: ubuntu-latest
    needs: lint-docker
    steps:
      - uses: actions/checkout@v4
      - name: Lint code
        run: |
          docker compose -f docker-compose.build.yml build main
          docker compose -f docker-compose.build.yml run main sh -c "pnpm run lint"

  audit:
    runs-on: ubuntu-latest
    needs: lint-typescript
    steps:
      - uses: actions/checkout@v4
      - name: Audit packages
        run: |
          docker compose -f docker-compose.build.yml build main
          docker compose -f docker-compose.build.yml run main sh -c "pnpm audit"
  test:
    runs-on: ubuntu-latest
    needs: lint-typescript
    steps:
      - uses: actions/checkout@v4
      - name: Test code
        run: |
          docker compose -f docker-compose.build.yml build install prerelease

  typescript-build-bank:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          docker compose -f docker-compose.build.yml build main
          docker compose -f docker-compose.build.yml run main sh -c "pnpm run build:bank"

  typescript-build-miner:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          docker compose -f docker-compose.build.yml build main
          docker compose -f docker-compose.build.yml run main sh -c "pnpm run build:miner"
