name: Feature actions

on:
  push:
    branches-ignore:
      - "main"

jobs:
  lint-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint dockerfile
        run: docker run --rm -i -v "$PWD"/hadolint.yml:/.config/hadolint.yaml hadolint/hadolint < .docker/Dockerfile

  install-packages:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - uses: actions/checkout@v4
      - name: Build source image
        run: docker compose -f docker-compose.build.yml build main
      - name: Install
        run: docker compose -f docker-compose.build.yml -v $PWD:/usr/app run main corepack install && pnpm i
      - name: Compress files
        run: tar -czf pnpm-packages.tar.gz node_modules
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pnpm-packages
          path: pnpm-packages.tar.gz

  lint-typescript:
    runs-on: ubuntu-latest
    needs: install-packages
    steps:
      - uses: actions/checkout@v4
      - name: Download application artifacts
        uses: actions/download-artifact@v4
        with:
          name: pnpm-packages
      - name: Extract artifacts
        run: tar -xvf pnpm-packages.tar.gz
      - name: Download blockchain image
        uses: actions/download-artifact@v4
        with:
          name: blockchain-image
          path: /tmp
      - name: Load blockchain image
        run: docker load < /tmp/blockchain-image.tar
      - name: Lint code
        run: docker run --rm blockchain:source -v $PWD:/usr/app pnpm run lint

  audit:
    runs-on: ubuntu-latest
    needs: lint-typescript
    container: exilesprx/blockchain:source
    steps:
      - uses: actions/checkout@v4
      - name: Audit packages
        run: pnpm audit

  test:
    runs-on: ubuntu-latest
    needs: lint-typescript
    container: exilesprx/blockchain:source
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: pnpm-packages
      - name: Extract artifacts
        run: tar -xvf pnpm-packages.tar.gz
      - name: Test code
        run: pnpm run test

  typescript-build-bank:
    runs-on: ubuntu-latest
    needs: test
    container: exilesprx/blockchain:source
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: pnpm-packages
      - name: Extract artifacts
        run: tar -xvf pnpm-packages.tar.gz
      - name: Build
        run: pnpm run build:bank

  typescript-build-miner:
    runs-on: ubuntu-latest
    needs: test
    container: exilesprx/blockchain:source
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: pnpm-packages
      - name: Extract artifacts
        run: tar -xvf pnpm-packages.tar.gz
      - name: Build
        run: pnpm run build:miner
