name: Feature actions

on:
  push:
    branches-ignore:
      - "main"

#I'm not a fan of redundant builds since it increases build times, but artifacts are also costly
jobs:
  lint-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint dockerfile
        run: docker run --rm -i -v "$PWD"/hadolint.yml:/.config/hadolint.yaml hadolint/hadolint < .docker/Dockerfile

  install-packages:
    runs-on: ubuntu-latest
    needs: lint-docker
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: docker compose -f docker-compose.build.yml run -u root -v $PWD:/usr/app main sh -c "pnpm i"
      - name: Compress files
        run: tar -czf pnpm-packages.tar.gz node_modules
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pnpm-packages
          path: pnpm-packages.tar.gz

  lint-typescript:
    runs-on: ubuntu-latest
    needs: install-packages
    steps:
      - uses: actions/checkout@v4
      - name: Download application artifacts
        uses: actions/download-artifact@v4
        with:
          name: pnpm-packages
      - name: Extract artifacts
        run: tar -xvf pnpm-packages.tar.gz
      - name: Lint code
        run: docker compose -f docker-compose.build.yml run -v $PWD:/usr/app main sh -c "pnpm run lint"

  audit:
    runs-on: ubuntu-latest
    needs: lint-typescript
    steps:
      - uses: actions/checkout@v4
      - name: Audit packages
        run: docker compose -f docker-compose.build.yml run -v $PWD:/usr/app main sh -c "pnpm audit"

  test:
    runs-on: ubuntu-latest
    needs: lint-typescript
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: pnpm-packages
      - name: Extract artifacts
        run: tar -xvf pnpm-packages.tar.gz
      - name: Test code
        run: docker compose -f docker-compose.build.yml run -v $PWD:/usr/app main sh -c "pnpm run test"

  typescript-build-bank:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: pnpm-packages
      - name: Extract artifacts
        run: tar -xvf pnpm-packages.tar.gz
      - name: Build
        run: docker compose -f docker-compose.build.yml run -u root -v $PWD:/usr/app main sh -c "pnpm run build:bank"

  typescript-build-miner:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: pnpm-packages
      - name: Extract artifacts
        run: tar -xvf pnpm-packages.tar.gz
      - name: Build
        run: docker compose -f docker-compose.build.yml run -u root -v $PWD:/usr/app main sh -c "pnpm run build:miner"
