name: Install Packages

on:
  workflow_call

jobs:

  install-packages:
    runs-on: ubuntu-latest
    container: exilesprx/blockchain:source
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: pnpm-packages
          path: node_modules

      - name: Install
        run: pnpm i