name: Install Packages

on:
  workflow_call

jobs:

  install-packages:
    runs-on: ubuntu-latest
    container: exilesprx/blockchain:source
    steps:
      - uses: actions/checkout@v3

      - name: Cache packages
        uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install
        run: pnpm i