name: Install Packages

on:
  workflow_call

jobs:

  install-packages:
    runs-on: ubuntu-latest
    container:
      image: exilesprx/blockchain:source
    steps:
      - uses: actions/checkout@v4

      - name: Corepack
        run: corepack install

      - name: Install
        run: pnpm i

      - name: Compress files
        run: tar -czf pnpm-packages.tar.gz node_modules

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pnpm-packages
          path: pnpm-packages.tar.gz