name: Install Packages

on:
  workflow_call

jobs:

  install-packages:
    runs-on: ubuntu-latest
    container: exilesprx/blockchain:source
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: pnpm i

      - name: Compress files
        run: tar -czf node_modules.tar.gz node_modules

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pnpm-packages
          path: node_modules.tar.gz