name: Lint

on:
  push:
    branches_ignore:
      - 'main'

jobs:
  lint-typescript:
    runs-on: ubuntu-latest
    container: exilesprx\blockchain:develop
    steps:
      - uses: actions/checkout@v3

      - name: Install packges
        run: pnpm i

      - name: Lint code
        run: pnpm run lint

  lint-docker:
    runs-on: ubuntu-latest
    container: exilesprx\blockchain:develop
    steps:
      - uses: actions/checkout@v3

      - name: Lint dockerfile
        run: docker run --rm -i -v "$PWD"/hadolint.yml:/.config/hadolint.yaml hadolint/hadolint < .docker/Dockerfile