name: Lint

on:
  push:
    branches_ignore:
      - 'main'

jobs:
  lint-typescript:
    runs-on: exilesprx\blockchain:develop
    steps:
      - uses: actions/checkout@v3

      - name: Install packges
        run: pnpm i

      - name: Lint code
        run: pnpm run lint

  lint-docker:
    runs-on: ubunti-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Lint
        run: docker run --rm -i -v "$PWD"/hadolint.yml:/.config/hadolint.yaml hadolint/hadolint < .docker/Dockerfile