name: Release actions

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  docker-build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: pnpm-packages

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          docker compose -f docker-compose.version.yml build version
          docker compose -f docker-compose.version.yml push version
