name: Release actions

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  install-packages:
    uses: ./.github/workflows/install-packages.yml

  docker-build-release:
    runs-on: ubuntu-latest
    needs: install-packages
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: pnpm-packages

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          docker compose -f docker-compose.version.yml build --pull version
          docker compose -f docker-compose.version.yml push version