name: Release actions

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  install-packages:
    uses: ./.github/workflows/install-packages.yml

  docker-build-release:
    runs-on: ubuntu-latest
    needs: install-packages
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install packages
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm i

      - name: Build
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          docker compose -f docker-compose.version.yml build --pull version
          docker compose -f docker-compose.version.yml push version